### ISSUE TITLE
add honors and awards to cv

### ISSUE THREAD

**Issue by collinschwantes** [collinschwantes/collinschwantes.github.io#5]
```
- title: Honors and Awards
  type: time_table
  contents:
    - year: 1921
      items:
        - Nobel Prize in Physics
        - Matteucci Medal
    - year: 2029
      items:
        - Max Planck Medal
 ```
